version: "3"

services:
  db:
    container_name: sig-db
    image: postgres
    restart: always
    env_file:
      - backend/.env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itemz-db

  node:
    container_name: sig-back
    env_file:
      - backend/.env.prod
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - '3001:3001'
    depends_on:
      - db

  react:
    container_name: sig-front
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - '3000:80'

  nginx:
    container_name: sig-nginx
    depends_on:
      - node
      - react
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
